port: 8000
loglevel: debug
storage_path: ./storage
auth_config:
  jwt_secret: "superdupersecret"
  jwt_ttl: 72h
db_config:
  host: postgres
  user: shopapi
  password: jw8s0F4
  db_name: onlineshop
  port: 5432
